//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mirelle {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mirelle.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The call to method &apos;{0}&apos; is ambigious: at least &apos;{1}&apos; and &apos;{2}&apos; match!.
        /// </summary>
        internal static string errAmbigiousCall {
            get {
                return ResourceManager.GetString("errAmbigiousCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression within an array literal must be enclosed in parens!.
        /// </summary>
        internal static string errArrayExpressionParensExpected {
            get {
                return ResourceManager.GetString("errArrayExpressionParensExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A type specifier is required when defining an array! Please cast the null to desired type using the &apos;as&apos; operator!.
        /// </summary>
        internal static string errArrayItemNull {
            get {
                return ResourceManager.GetString("errArrayItemNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add an item of type &apos;{0}&apos; to an array of &apos;{1}&apos;!.
        /// </summary>
        internal static string errArrayTypeMismatch {
            get {
                return ResourceManager.GetString("errArrayTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment target and expression must be of the same type, cannot assign &apos;{0}&apos; to &apos;{1}&apos;!.
        /// </summary>
        internal static string errAssignTypeMismatch {
            get {
                return ResourceManager.GetString("errAssignTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The keyword &apos;at&apos; is expected after &apos;once&apos;!.
        /// </summary>
        internal static string errAtExpected {
            get {
                return ResourceManager.GetString("errAtExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An inherited type cannot be autoconstructed!.
        /// </summary>
        internal static string errAutoconstructInherited {
            get {
                return ResourceManager.GetString("errAutoconstructInherited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; contains no fields and cannot be autoconstructed!.
        /// </summary>
        internal static string errAutoconstructNoFields {
            get {
                return ResourceManager.GetString("errAutoconstructNoFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This type has already been marked as autoconstructed!.
        /// </summary>
        internal static string errAutoconstructRepeated {
            get {
                return ResourceManager.GetString("errAutoconstructRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary operations can only be performed on integers!.
        /// </summary>
        internal static string errBinaryOperatorIntExpected {
            get {
                return ResourceManager.GetString("errBinaryOperatorIntExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A code block should be enclosed in curly braces!.
        /// </summary>
        internal static string errBlockCurlyBrace {
            get {
                return ResourceManager.GetString("errBlockCurlyBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A boolean expression is expected!.
        /// </summary>
        internal static string errBoolExpected {
            get {
                return ResourceManager.GetString("errBoolExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop control statements must be inside a loop!.
        /// </summary>
        internal static string errBreakRedoOutsideLoop {
            get {
                return ResourceManager.GetString("errBreakRedoOutsideLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array types cannot be casted!.
        /// </summary>
        internal static string errCastArray {
            get {
                return ResourceManager.GetString("errCastArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local fields and methods cannot be used in closures!.
        /// </summary>
        internal static string errClosuredMember {
            get {
                return ResourceManager.GetString("errClosuredMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The @ pointer cannot be used in closures!.
        /// </summary>
        internal static string errClosuredThis {
            get {
                return ResourceManager.GetString("errClosuredThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A comma is expected!.
        /// </summary>
        internal static string errCommaExpected {
            get {
                return ResourceManager.GetString("errCommaExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The constant value is either too large or too small for it&apos;s type!.
        /// </summary>
        internal static string errConstantOverflow {
            get {
                return ResourceManager.GetString("errConstantOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A constant value is expected!.
        /// </summary>
        internal static string errConstExpected {
            get {
                return ResourceManager.GetString("errConstExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot construct &apos;{0}&apos; because it is an enum, not a type!.
        /// </summary>
        internal static string errConstructEnum {
            get {
                return ResourceManager.GetString("errConstructEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; does not have a constructor accepting &apos;{1}&apos;!.
        /// </summary>
        internal static string errConstructorNotFound {
            get {
                return ResourceManager.GetString("errConstructorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; does not have a default constructor!.
        /// </summary>
        internal static string errDefaultConstructorNotFound {
            get {
                return ResourceManager.GetString("errDefaultConstructorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A key-value separator &apos;=&gt;&apos; is expected!.
        /// </summary>
        internal static string errDictArrowExpected {
            get {
                return ResourceManager.GetString("errDictArrowExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A dict literal must be enclosed in curly braces!.
        /// </summary>
        internal static string errDictCurlyBrace {
            get {
                return ResourceManager.GetString("errDictCurlyBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A dict key or value must be a string expression!.
        /// </summary>
        internal static string errDictItemTypeMismatch {
            get {
                return ResourceManager.GetString("errDictItemTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both key and item variables must be specified when iterating a dict! To iterate keys or values only, use the dict.keys and dict.values methods in the &apos;in&apos; clause!.
        /// </summary>
        internal static string errDictIterKeyRequired {
            get {
                return ResourceManager.GetString("errDictIterKeyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting a string, an identifier or an expression in parens for a dict key!.
        /// </summary>
        internal static string errDictKeyExpected {
            get {
                return ResourceManager.GetString("errDictKeyExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;do&apos; keyword is expected!.
        /// </summary>
        internal static string errDoExpected {
            get {
                return ResourceManager.GetString("errDoExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A matrix-closing double square bracket is expected!.
        /// </summary>
        internal static string errDoubleSquareBracketExpected {
            get {
                return ResourceManager.GetString("errDoubleSquareBracketExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not static and cannot be accessed from a static context!.
        /// </summary>
        internal static string errDynamicFromStatic {
            get {
                return ResourceManager.GetString("errDynamicFromStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emitter condition must be a boolean expression!.
        /// </summary>
        internal static string errEmitConditionExpected {
            get {
                return ResourceManager.GetString("errEmitConditionExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emitter distribution expected!.
        /// </summary>
        internal static string errEmitDistributionExpected {
            get {
                return ResourceManager.GetString("errEmitDistributionExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emitter event limit must be an integer!.
        /// </summary>
        internal static string errEmitLimitExpected {
            get {
                return ResourceManager.GetString("errEmitLimitExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emitter step must be a floating point number or an integer!.
        /// </summary>
        internal static string errEmitStepExpected {
            get {
                return ResourceManager.GetString("errEmitStepExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An array must contain at least one item!.
        /// </summary>
        internal static string errEmptyArray {
            get {
                return ResourceManager.GetString("errEmptyArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A matrix must contain at least one item!.
        /// </summary>
        internal static string errEmptyMatrix {
            get {
                return ResourceManager.GetString("errEmptyMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enums cannot inherit from types!.
        /// </summary>
        internal static string errEnumParent {
            get {
                return ResourceManager.GetString("errEnumParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value named &apos;{0}&apos; already exists in the enum &apos;{1}&apos;!.
        /// </summary>
        internal static string errEnumRedefinition {
            get {
                return ResourceManager.GetString("errEnumRedefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An enum value name is expected!.
        /// </summary>
        internal static string errEnumValueNameExpected {
            get {
                return ResourceManager.GetString("errEnumValueNameExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting a constant, array, variable, method call, object creation or a subexpression in parens!.
        /// </summary>
        internal static string errExpressionExpected {
            get {
                return ResourceManager.GetString("errExpressionExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is built-in and cannot be extended with methods and properties!.
        /// </summary>
        internal static string errExtendBuiltInType {
            get {
                return ResourceManager.GetString("errExtendBuiltInType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A field name should start with a @ sign!.
        /// </summary>
        internal static string errFieldAtmarkExpected {
            get {
                return ResourceManager.GetString("errFieldAtmarkExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is a field and cannot be invoked like a method!.
        /// </summary>
        internal static string errFieldInvoke {
            get {
                return ResourceManager.GetString("errFieldInvoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A field name is expected!.
        /// </summary>
        internal static string errFieldNameExpected {
            get {
                return ResourceManager.GetString("errFieldNameExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; does not exist in type &apos;{1}&apos;!.
        /// </summary>
        internal static string errFieldNotFound {
            get {
                return ResourceManager.GetString("errFieldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A field cannot be used outside methods of a type!.
        /// </summary>
        internal static string errFieldOutsideType {
            get {
                return ResourceManager.GetString("errFieldOutsideType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A field named &apos;{0}&apos; already exists in type &apos;{1}&apos;!.
        /// </summary>
        internal static string errFieldRedefinition {
            get {
                return ResourceManager.GetString("errFieldRedefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; was already compiled!.
        /// </summary>
        internal static string errFileAlreadyCompiled {
            get {
                return ResourceManager.GetString("errFileAlreadyCompiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; was not found!.
        /// </summary>
        internal static string errFileNotFound {
            get {
                return ResourceManager.GetString("errFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An array, range or dict expression is expected for iteration!.
        /// </summary>
        internal static string errForIterableExpected {
            get {
                return ResourceManager.GetString("errForIterableExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; was not found in any visible types!.
        /// </summary>
        internal static string errGlobalMethodNotFound {
            get {
                return ResourceManager.GetString("errGlobalMethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;use&apos; and &apos;include&apos; commands cannot be nested!.
        /// </summary>
        internal static string errGlobalStmtInLocal {
            get {
                return ResourceManager.GetString("errGlobalStmtInLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A field or a method name is expected!.
        /// </summary>
        internal static string errIdentifierExpected {
            get {
                return ResourceManager.GetString("errIdentifierExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identifier &apos;{0}&apos; does not exist in current context!.
        /// </summary>
        internal static string errIdentifierUnresolved {
            get {
                return ResourceManager.GetString("errIdentifierUnresolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file name or path is expected!.
        /// </summary>
        internal static string errIncludePathExpected {
            get {
                return ResourceManager.GetString("errIncludePathExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types &apos;{0}&apos; and &apos;{1}&apos; cannot be compared!.
        /// </summary>
        internal static string errIncomparableTypes {
            get {
                return ResourceManager.GetString("errIncomparableTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid expression type signature!.
        /// </summary>
        internal static string errIncorrectSignature {
            get {
                return ResourceManager.GetString("errIncorrectSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lefthand expression is not a matrix!.
        /// </summary>
        internal static string errIndexingNotAMatrix {
            get {
                return ResourceManager.GetString("errIndexingNotAMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lefthand expression is not an array!.
        /// </summary>
        internal static string errIndexingNotAnArray {
            get {
                return ResourceManager.GetString("errIndexingNotAnArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;in&apos; keyword is expected!.
        /// </summary>
        internal static string errInExpected {
            get {
                return ResourceManager.GetString("errInExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is built-in and cannot be inherited from!.
        /// </summary>
        internal static string errInheritBuiltInType {
            get {
                return ResourceManager.GetString("errInheritBuiltInType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot inherit from &apos;{0}&apos; because it&apos;s an enum, not a type!.
        /// </summary>
        internal static string errInheritEnum {
            get {
                return ResourceManager.GetString("errInheritEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An integer or a float expression is expected!.
        /// </summary>
        internal static string errIntFloatExpected {
            get {
                return ResourceManager.GetString("errIntFloatExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An array or matrix index must be of &apos;int&apos; type!.
        /// </summary>
        internal static string errIntIndexExpected {
            get {
                return ResourceManager.GetString("errIntIndexExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot cast object of type &apos;{0}&apos; to type &apos;{1}&apos;!.
        /// </summary>
        internal static string errInvalidCast {
            get {
                return ResourceManager.GetString("errInvalidCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot cast a null-pointer to type &apos;{0}&apos;!.
        /// </summary>
        internal static string errInvalidNullCast {
            get {
                return ResourceManager.GetString("errInvalidNullCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot invert an object of type &apos;{0}&apos;!.
        /// </summary>
        internal static string errInvertType {
            get {
                return ResourceManager.GetString("errInvertType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s only possible to assign to a variable, field, array or matrix item!.
        /// </summary>
        internal static string errLvalueExpected {
            get {
                return ResourceManager.GetString("errLvalueExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expressions within a matrix literal must be enclosed in parens!.
        /// </summary>
        internal static string errMatrixExpressionParensExpected {
            get {
                return ResourceManager.GetString("errMatrixExpressionParensExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A matrix must be assigned to a variable before it can be used in an expression!.
        /// </summary>
        internal static string errMatrixInExpression {
            get {
                return ResourceManager.GetString("errMatrixInExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A matrix item can only be an int or a float expression!.
        /// </summary>
        internal static string errMatrixItemTypeMismatch {
            get {
                return ResourceManager.GetString("errMatrixItemTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each line in a must contain equal number of items (&apos;{0}&apos;), but line {1} has {2} items!.
        /// </summary>
        internal static string errMatrixLineLengthMismatch {
            get {
                return ResourceManager.GetString("errMatrixLineLengthMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method body should be enclosed in curly braces!.
        /// </summary>
        internal static string errMethodCurlyBrace {
            get {
                return ResourceManager.GetString("errMethodCurlyBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A method name is expected!.
        /// </summary>
        internal static string errMethodNameExpected {
            get {
                return ResourceManager.GetString("errMethodNameExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No method named &apos;{0}&apos; accepting &apos;{1}&apos; was found!.
        /// </summary>
        internal static string errMethodNotFound {
            get {
                return ResourceManager.GetString("errMethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No method named &apos;{0}&apos; accepting &apos;{1}&apos; was found in type &apos;{2}&apos;!.
        /// </summary>
        internal static string errMethodNotFoundInType {
            get {
                return ResourceManager.GetString("errMethodNotFoundInType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A method named &apos;{0}&apos; already exists in type &apos;{1}&apos; and has identical set of parameters!.
        /// </summary>
        internal static string errMethodRedefinition {
            get {
                return ResourceManager.GetString("errMethodRedefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A statement should be terminated with a newline!.
        /// </summary>
        internal static string errNewLineExpected {
            get {
                return ResourceManager.GetString("errNewLineExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot be called as a static method!.
        /// </summary>
        internal static string errNonStaticMethod {
            get {
                return ResourceManager.GetString("errNonStaticMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all code paths in method &apos;{0}&apos; return a value!.
        /// </summary>
        internal static string errNotAllPathsReturn {
            get {
                return ResourceManager.GetString("errNotAllPathsReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot invoke methods or access fields of an unspecified type!.
        /// </summary>
        internal static string errNullAccessor {
            get {
                return ResourceManager.GetString("errNullAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator &apos;{0}&apos; cannot be used on types &apos;{1}&apos; and &apos;{2}&apos;!.
        /// </summary>
        internal static string errOperatorTypesMismatch {
            get {
                return ResourceManager.GetString("errOperatorTypesMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter named &apos;{0}&apos; is already defined for this method!.
        /// </summary>
        internal static string errParameterNameDuplicated {
            get {
                return ResourceManager.GetString("errParameterNameDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A parameter name is expected!.
        /// </summary>
        internal static string errParameterNameExpected {
            get {
                return ResourceManager.GetString("errParameterNameExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters must be separated by commas!.
        /// </summary>
        internal static string errParamSeparatorExpected {
            get {
                return ResourceManager.GetString("errParamSeparatorExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A closing paren is expected!.
        /// </summary>
        internal static string errParenExpected {
            get {
                return ResourceManager.GetString("errParenExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The planner method must accept two parameters: &apos;flow[]&apos; and &apos;symbol&apos;!.
        /// </summary>
        internal static string errPlannerArgsMismatch {
            get {
                return ResourceManager.GetString("errPlannerArgsMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting a planner method name, either static or instance-based, without parameters!.
        /// </summary>
        internal static string errPlannerExpression {
            get {
                return ResourceManager.GetString("errPlannerExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The planner method must return a &apos;symbol&apos;!.
        /// </summary>
        internal static string errPlannerTypeMismatch {
            get {
                return ResourceManager.GetString("errPlannerTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range limits must be of &apos;int&apos; type!.
        /// </summary>
        internal static string errRangeLimitsIntExpected {
            get {
                return ResourceManager.GetString("errRangeLimitsIntExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects of type &apos;{0}&apos; cannot be compared as &apos;less&apos; and &apos;greater&apos;!.
        /// </summary>
        internal static string errRelationIncomparableTypes {
            get {
                return ResourceManager.GetString("errRelationIncomparableTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A return expression is expected!.
        /// </summary>
        internal static string errReturnExpressionExpected {
            get {
                return ResourceManager.GetString("errReturnExpressionExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return statements are only allowed inside a method!.
        /// </summary>
        internal static string errReturnOutsideMethod {
            get {
                return ResourceManager.GetString("errReturnOutsideMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; requires return type &apos;{1}&apos;, cannot return a &apos;{2}&apos;!.
        /// </summary>
        internal static string errReturnTypeMismatch {
            get {
                return ResourceManager.GetString("errReturnTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; is declared as &apos;void&apos; and cannot return a value!.
        /// </summary>
        internal static string errReturnVoidExpected {
            get {
                return ResourceManager.GetString("errReturnVoidExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot have multiple planner simulations within one program!.
        /// </summary>
        internal static string errSimulateMultiple {
            get {
                return ResourceManager.GetString("errSimulateMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor count must be an integer!.
        /// </summary>
        internal static string errSimulateProcessorsInt {
            get {
                return ResourceManager.GetString("errSimulateProcessorsInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue length must be an integer!.
        /// </summary>
        internal static string errSimulateQueueInt {
            get {
                return ResourceManager.GetString("errSimulateQueueInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A simulation type (&quot;any&quot; or &quot;planner&quot;) is expected!.
        /// </summary>
        internal static string errSimulateType {
            get {
                return ResourceManager.GetString("errSimulateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The special method &apos;{0}&apos; must return a &apos;{1}&apos;!.
        /// </summary>
        internal static string errSpecialIncorrectReturnType {
            get {
                return ResourceManager.GetString("errSpecialIncorrectReturnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; identifier is special and cannot be a an enum value!.
        /// </summary>
        internal static string errSpecialInEnum {
            get {
                return ResourceManager.GetString("errSpecialInEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression must be an array to use splat assignment!.
        /// </summary>
        internal static string errSplatArrayExpected {
            get {
                return ResourceManager.GetString("errSplatArrayExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A square bracket is expected!.
        /// </summary>
        internal static string errSquareBracketExpected {
            get {
                return ResourceManager.GetString("errSquareBracketExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The constructor in type &apos;{0}&apos; cannot be marked as static!.
        /// </summary>
        internal static string errStaticConstructor {
            get {
                return ResourceManager.GetString("errStaticConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A string expression is expected!.
        /// </summary>
        internal static string errStringExpected {
            get {
                return ResourceManager.GetString("errStringExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The self-reference cannot used in a static context!.
        /// </summary>
        internal static string errThisInStaticContext {
            get {
                return ResourceManager.GetString("errThisInStaticContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tilde (~) is expected!.
        /// </summary>
        internal static string errTildeExpected {
            get {
                return ResourceManager.GetString("errTildeExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An emitter definition must contain either &quot;with&quot; or &quot;every&quot; clause, or both!.
        /// </summary>
        internal static string errTimeSpanExpected {
            get {
                return ResourceManager.GetString("errTimeSpanExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type body should be enclosed in curly braces!.
        /// </summary>
        internal static string errTypeCurlyBrace {
            get {
                return ResourceManager.GetString("errTypeCurlyBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; does not have a field or a method named &apos;{1}&apos;!.
        /// </summary>
        internal static string errTypeIdentifierUnresolved {
            get {
                return ResourceManager.GetString("errTypeIdentifierUnresolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A type name is expected!.
        /// </summary>
        internal static string errTypeNameExpected {
            get {
                return ResourceManager.GetString("errTypeNameExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types cannot be nested!.
        /// </summary>
        internal static string errTypeNesting {
            get {
                return ResourceManager.GetString("errTypeNesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is not defined!.
        /// </summary>
        internal static string errTypeNotFound {
            get {
                return ResourceManager.GetString("errTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parent type, &apos;{0}&apos;, must have a default constructor!.
        /// </summary>
        internal static string errTypeParentDefaultCtor {
            get {
                return ResourceManager.GetString("errTypeParentDefaultCtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot define type &apos;{0}&apos; because parent type &apos;{1}&apos; is not defined!.
        /// </summary>
        internal static string errTypeParentNotFound {
            get {
                return ResourceManager.GetString("errTypeParentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; was already defined!.
        /// </summary>
        internal static string errTypeRedefinition {
            get {
                return ResourceManager.GetString("errTypeRedefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A type signature is expected!.
        /// </summary>
        internal static string errTypeSignatureExpected {
            get {
                return ResourceManager.GetString("errTypeSignatureExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A type body can only consist of field and method definitions!.
        /// </summary>
        internal static string errTypeUnknownStmt {
            get {
                return ResourceManager.GetString("errTypeUnknownStmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting an int or a float value for the &apos;{0}&apos; operator!.
        /// </summary>
        internal static string errUnaryOperatorNumericExpected {
            get {
                return ResourceManager.GetString("errUnaryOperatorNumericExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected &apos;{0}&apos;..
        /// </summary>
        internal static string errUnexpectedLexem {
            get {
                return ResourceManager.GetString("errUnexpectedLexem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown lexem!.
        /// </summary>
        internal static string errUnknownLexem {
            get {
                return ResourceManager.GetString("errUnknownLexem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; has already been marked as &apos;used&apos;!.
        /// </summary>
        internal static string errUseTypeDuplicated {
            get {
                return ResourceManager.GetString("errUseTypeDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables should be assigned a value at declaration!.
        /// </summary>
        internal static string errVariableAssignmentExpected {
            get {
                return ResourceManager.GetString("errVariableAssignmentExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A type specifier is required when defining a variable! Please cast the null to desired type using the &apos;as&apos; operator!.
        /// </summary>
        internal static string errVariableDefinedNull {
            get {
                return ResourceManager.GetString("errVariableDefinedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variable definition cannot be the only statement in the code block!.
        /// </summary>
        internal static string errVariableDefinitionOnly {
            get {
                return ResourceManager.GetString("errVariableDefinitionOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A variable name is expected!.
        /// </summary>
        internal static string errVariableNameExpected {
            get {
                return ResourceManager.GetString("errVariableNameExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A variable named &apos;{0}&apos; already exists in current scope!.
        /// </summary>
        internal static string errVariableRedefinition {
            get {
                return ResourceManager.GetString("errVariableRedefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A variable named &apos;{0}&apos; is not defined!.
        /// </summary>
        internal static string errVariableUndefined {
            get {
                return ResourceManager.GetString("errVariableUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variable &apos;{0}&apos; cannot be assigned a void!.
        /// </summary>
        internal static string errVoidAssign {
            get {
                return ResourceManager.GetString("errVoidAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create an array or a matrix of voids!.
        /// </summary>
        internal static string errVoidCompoundType {
            get {
                return ResourceManager.GetString("errVoidCompoundType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use a void function or null value as a part of expression!.
        /// </summary>
        internal static string errVoidExpression {
            get {
                return ResourceManager.GetString("errVoidExpression", resourceCulture);
            }
        }
    }
}
